easy_admin:
    entities:
        Page:
            class: Opera\CoreBundle\Entity\Page
            list:
                fields: [ 'slug', 'title', 'status', 'route' ]
                actions: 
                    - edit
                    - delete
                    - { name: 'opera_admin_pages_blocks', type: 'route', label: 'Layout' } 
            form:
                fields:
                    - { type: 'tab' , label: 'Informations', icon: 'user' }
                    - title
                    - { property: 'slug', type_options: { required: false } }
                    - { property: 'status', type: 'choice', type_options: { choices: { 'published': 'published', 'draft': 'draft' } } }
                    - route
                    - { property: 'is_regexp', help: 'If is not a route and want dynamics params' }
                    - layout
                    - { type: 'tab' , label: 'SEO', icon: 'search' }
                    - { property: meta_keyword, type: textarea }
                    - { property: meta_description, type: textarea }
                    - { property: complementary_meta, type: textarea }

        Layout:
            class: Opera\CoreBundle\Entity\Layout
            form:
                fields:
                    - { property: 'configuration', type: 'Opera\AdminBundle\Form\JsonType' }
